version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db-folder:/var/lib/mysql
# Names our volume

